import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import guildsRouter from "./guilds";
import moderationRouter from "./moderation";
import automodRouter from "./automod";
import reactionRolesRouter from "./reaction-roles";
import commandsRouter from "./commands";
import welcomeRouter from "./welcome";
import remindersRouter from "./reminders";
import pollsRouter from "./polls";
import statsRouter from "./stats";
import leaveRouter from "./leave";
import webhookSenderRouter from "./webhook-sender";
import alwaysOnlineRouter from "./always-online";
import levelRolesRouter from "./level-roles";
import botRouter from "./bot";
import meRouter from "./me";
import selfRolesRouter from "./self-roles";
import ticketsRouter from "./tickets";
import applicationsRouter from "./applications";
import xpSettingsRouter from "./xp-settings";
import statsChannelsRouter from "./stats-channels";
import giveawaysRouter from "./giveaways";
import setupRouter from "./setup";
import rulesRouter from "./rules";
import inviteManagementRouter from "./invite-management";
import messageLogsRouter from "./message-logs";
import verificationRouter from "./verification";
import summaryRouter from "./summary";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/guilds", guildsRouter);
router.use("/guilds/:guildId", moderationRouter);
router.use("/guilds/:guildId", automodRouter);
router.use("/guilds/:guildId", reactionRolesRouter);
router.use("/guilds/:guildId", commandsRouter);
router.use("/guilds/:guildId", welcomeRouter);
router.use("/guilds/:guildId", remindersRouter);
router.use("/guilds/:guildId", pollsRouter);
router.use("/guilds/:guildId", leaveRouter);
router.use("/guilds/:guildId", webhookSenderRouter);
router.use("/guilds/:guildId", alwaysOnlineRouter);
router.use("/guilds/:guildId", levelRolesRouter);
router.use("/guilds/:guildId", selfRolesRouter);
router.use("/guilds/:guildId", ticketsRouter);
router.use("/guilds/:guildId", applicationsRouter);
router.use("/guilds/:guildId", xpSettingsRouter);
router.use("/guilds/:guildId", statsChannelsRouter);
router.use("/guilds/:guildId", giveawaysRouter);
router.use("/guilds/:guildId", setupRouter);
router.use("/guilds/:guildId", rulesRouter);
router.use("/guilds/:guildId", inviteManagementRouter);
router.use("/guilds/:guildId", messageLogsRouter);
router.use("/guilds/:guildId", verificationRouter);
router.use("/guilds/:guildId", summaryRouter);
router.use(botRouter);
router.use(meRouter);
router.use("/stats", statsRouter);

export default router;
